### PR TITLE
Add "api_key_file" to the config to (eventually) replace "api_key / config"

### PR DESCRIPTION
**Pull request by lazydroid**
## Description

New keyword introduced to the config file that allows to store credentials for the exchange as a separate file.
This should help to keep the credentials safe and avoid posting them in public forums when exchanging configs.

## Type of change

Please make your selection.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [x] Code Refactoring / future-proofing

## How Has This Been Tested?

Runs well on my PC

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by iThom — CHANGES_REQUESTED** [review]
Thanks for this PR.

I think version in README.md should be `2.39.0` and not `2.38.1` since you are adding a new feature and it's not a hotfix.

**Comment by lazydroid** [comment]
@iThom there's nothing major, everything works as it was before, except 5-line change and a small nagging message.

OTOH, if you feel that this requires a version change, please, feel free to adjust the version.

Thanks!

**Comment by iThom** [comment]
> @iThom there's nothing major, everything works as it was before, except for 5-line change and a small nagging message.
> 
> OTOH, if you feel that this requires a version change, this should not be a probelm.
> 
> Thanks!

This is the contribution rules for this project (@whittlem can you confirm ?):

For a version X.Y.Z

X is for major changes
Y is for new feature
Z is for hotfix

In your PR you are not fixing something but adding a new way to store the exchange API keys so it's considered as a new feature.

Thank you for your changes.

**Comment by lazydroid** [comment]
@iThom the changes you have requested are already in, may I have you approval?

**Comment by lazydroid** [comment]
@iThom it says below: "iThom requested changes ". if I have an approval it should say: " iThom approved these changes "

**Review by iThom — APPROVED** [review]

**Comment by iThom** [comment]
> @iThom it says below: "iThom requested changes ". if I have an approval it should say: " iThom approved these changes "

My bad, thanks, I thought I already did.

**Review by edrickrenan — APPROVED** [review]

**Review by whittlem — APPROVED** [review]
This is great. Thanks

**Pull request merged**
