### PR TITLE
Improve binance calls to increase max number of pairs per IP

### PR DESCRIPTION
**Pull request by bsda**
## Description

Every minute, the bot makes what seems to be redundant calls to the binance API. Because of these extra calls, we hit the binance API limits after running aproximately 20 pairs from the same machine.

I made some changes to the code to reuse the values from the first call made to avoid doing those repetitive calls.
I'm not yet 100% familiar with the code and I'm not sure if the way I did the work is acceptable, but it seems to work.

Some testing is needed to ensure we are not using stale data.

Feel free to make changes/suggest changes/improve the code

### Increase of at least 50% on the number of pairs we can run from a single IP.

**Approximate number of pairs we can run from single IP before change:**
Last action SELL: 20
Last action BUY: 20

**Approximate number of pairs we can run from single IP after change:**
Last action SELL: 60
Last action BUY: 40

The API limits are weight based and have a total of 1200 weight per IP per minute:

``` 
curl -s "https://api.binance.com/api/v3/exchangeInfo" | jq .rateLimits[0]
{
  "rateLimitType": "REQUEST_WEIGHT",
  "interval": "MINUTE",
  "intervalNum": 1,
  "limit": 1200
}
```

The amount of calls made to the authenticated api varies if the last call is BUY or SELL

## BEFORE CHANGES:

When last action is BUY, 8 calls

| time                       |  method |  url               |  weight | 
|----------------------------|---------|--------------------|---------| 
| 2021-09-02 23:56:59.640573 |  GET    |  /api/v3/account   |  10     | 
| 2021-09-02 23:56:59.944115 |  GET    |  /api/v3/account   |  10     | 
| 2021-09-02 23:57:00.252772 |  GET    |  /api/v3/allOrders |  10     | 
| 2021-09-02 23:57:01.683376 |  GET    |  /api/v3/klines    |  0      | 
| 2021-09-02 23:57:01.966465 |  GET    |  /api/v3/account   |  10     | 
| 2021-09-02 23:57:02.255228 |  GET    |  /api/v3/allOrders |  10     | 
| 2021-09-02 23:57:02.563820 |  GET    |  /api/v3/klines    |  0      | 
| 2021-09-02 23:57:02.850580 |  GET    |  /api/v3/account   |  10     | 

Total weight per pair, per minute = 60

When last action = SELL, 5 calls

| time                       |  method |  url                  |  weight | 
|----------------------------|---------|-----------------------|---------| 
| 2021-09-02 23:59:21.987201 |  GET    |  /api/v3/account      |  10     | 
| 2021-09-02 23:59:22.284704 |  GET    |  /api/v3/account      |  10     | 
| 2021-09-02 23:59:22.580623 |  GET    |  /api/v3/allOrders    |  10     | 
| 2021-09-02 23:59:22.911815 |  GET    |  /api/v3/exchangeInfo |  10     | 
| 2021-09-02 23:59:23.190072 |  GET    |  /api/v3/account      |  10     | 

Total weight per pair, per minute = 60

## AFTER CHANGES

When last action is BUY, 4 calls

| time                       |  method |  url               |  weight | 
|----------------------------|---------|--------------------|---------| 
| 2021-09-03 00:00:47.488276 |  GET    |  /api/v3/account   |  10     | 
| 2021-09-03 00:00:47.865492 |  GET    |  /api/v3/allOrders |  10     | 
| 2021-09-03 00:00:48.773620 |  GET    |  /api/v3/klines    |  0      | 
| 2021-09-03 00:00:49.113299 |  GET    |  /api/v3/klines    |  0      | 

Total weight per pair, per minute = 20

When last action = SELL

| time                       |  method |  url                  |  weight | 
|----------------------------|---------|-----------------------|---------| 
| 2021-09-03 00:01:56.362520 |  GET    |  /api/v3/account      |  10     | 
| 2021-09-03 00:01:56.658150 |  GET    |  /api/v3/allOrders    |  10     | 
| 2021-09-03 00:01:56.972427 |  GET    |  /api/v3/exchangeInfo |  10     | 

Total weight per pair, per minute = 30
Fixes # (issue)

## Type of change

Please make your selection.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [ ] Code Refactoring / future-proofing

## How Has This Been Tested?

Running the bot with both last action = SELL and BUY

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by whittlem — APPROVED** [review]

**Comment by whittlem** [comment]
This looks great but I see you are "caching" the account balance. Will it only check for an account balance once? The bot should have some understanding if the balance has changed without having to restart. I'll add this into beta so we can test but looks good. Thanks.

**Comment by whittlem** [comment]
@bsda, thanks. Can you provide a one line description of what this change is for the CHANGELOG.md?

**Comment by bsda** [comment]
> This looks great but I see you are "caching" the account balance. Will it only check for an account balance once? The bot should have some understanding if the balance has changed without having to restart. I'll add this into beta so we can test but looks good. Thanks.

Hey @whittlem, The balance is checked once per minute, instead of 2 or 3 times per minute, I believe that because the caching only happens after the first call, I don't think this will be an issue, as the balance will be updated in the next minute. I'll do some testing by changing the balances manually

**Comment by bsda** [comment]
> @bsda, thanks. Can you provide a one line description of what this change is for the CHANGELOG.md?

Cache responses from binance api to avoid duplicate calls and avoid hitting api limits when running multiple bots.

**Comment by whittlem** [comment]
Thanks @mimusica, I don't see this PR in the list.

**Comment by whittlem** [comment]
I want roll everything back to before PR 472

**Comment by bsda** [comment]
@whittlem please go ahead and revert it, I can't spend time on it now, I'll review it and test coinbase before submitting again.

**Pull request merged**
