### PR TITLE
add new coinbase key type

### PR DESCRIPTION
**Pull request by bsvicente**
resolve issue https://github.com/whittlem/pycryptobot/issues/851

### CODE REVIEW

**Comment by bsvicente** [comment]
@whittlem maybe 8.3.0

**Comment by gibbstp** [comment]
@bsvicente I am getting a "{MARTKET} 900  ValueError('Length mismatch: Expected axis has 6 elements, new values have 5 elements')" when the bot is set to live on coinbase. Are you getting the same error?

**Comment by bsvicente** [comment]
@gibbstp i saw it, but im still doing some tests, maybe they have changed smth on their api.

**Comment by shervin422** [comment]
The changes worked for me! Many thanks @bsvicente

**Pull request closed without merging**
