### PR TITLE
[feature] Python version check, minimum python version is 3.6

### PR DESCRIPTION
**Pull request by mimusica**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please make your selection.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [ ] Code Refactoring / future-proofing

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by whittlem** [comment]
@mimusica, thanks. This version requirement shouldn't really apply anymore. I re-wrote the Binance API code. The bot should run with any 3.x version now. Can you confirm on the latest version you are not able to run the bot on less than 3.9.x?

**Comment by mimusica** [comment]
I saw that printstatements are used in different ways.

There is a mix of the old python2 and the newer f string formatting. I'm
not 100% certain, but I think that the f string only got introduced as of
python3.6?

We need to double check that to be certain.

Kind regards,

Op ma 6 sep. 2021 16:19 schreef Michael Whittle ***@***.***>:

**Comment by mimusica** [comment]
https://docs.python.org/3/whatsnew/3.6.html

indeed the f strings have been implemented as of python 3.6

I will modify this pr and push it again.

**Comment by mimusica** [comment]
To give you an idea of what I mean:

https://github.com/whittlem/pycryptobot/blob/2623aa624cde375a47f6f569ea76be39382f08f2/pycryptobot.py#L860 is an example of an f string

while the following is < python3.6 compatible:
https://github.com/whittlem/pycryptobot/blob/2623aa624cde375a47f6f569ea76be39382f08f2/pycryptobot.py#L889


Conclusion:
minimum python version = python3.6

You can verify my pr again @whittlem

**Comment by whittlem** [comment]
That's great mate, thanks for looking into this. So it looks like 3.6 is the minimum now. I will merge it in. Great update, thank you.

**Pull request merged**
