### PR TITLE
Allow telegram client id's of 7 -10 digits

### PR DESCRIPTION
**Pull request by lvlie**
It seems my telegram client_id is 7 digits instead of 10. This PR allows for 7-10 digits for the client_id. 

Confirmed this works for me:
image

My editor automatically removed erroneous whitespaces, hope you dont mind :)

### CODE REVIEW

**Comment by iThom** [comment]
Hello,

Same problem there, thanks for the PR.

**Comment by lvlie** [comment]
Apologies for the extra commit, am preparing a second PR for a Dockerfile and docker-compose.yaml but putting that in a new branch instead...

**Review by whittlem — APPROVED** [review]

**Comment by whittlem** [comment]
Thanks for your contribution.

**Comment by lvlie** [comment]
No problem! Github is not my friend today, merged the docker branch by accident.... (Not using github for job) will make sure the github actions actually work in a following PR with a short description on what you'd need to do on your end to actually automatically build the container and push it to the github container registry

**Pull request merged**
