### PR TITLE
Unified granularity

### PR DESCRIPTION
**Pull request by dthevenin**
## Description

Here the description of the issue: https://github.com/whittlem/pycryptobot/issues/203

Fixes # (issue)

## Type of change

Please make your selection.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [x] Code Maintainability / comments
- [x] Code Refactoring / future-proofing

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by dthevenin** [comment]
I did not pay attention... my editor did a `code styling fix` when I did commit the last change.
I will break down the last commit to make more visible the change.

**Comment by marioK93** [comment]
I think the changes on the Coinbase side look good, have tested them myself and they work

When using Binance though in the printout i think you should keep it as displaying the original value enetered by the user so there isn't a difference between what is specified as the granularity and what is displayed back

**Comment by whittlem** [comment]
Do not make breaking changes. Unifying granularity would not be backward compatible. I don't want people's bots breaking and forcing them to update their config.json's. I want it how it was using the official granularity for the exchanges as per the API documentation. Integer options for Coinbase and string options for Binance. There are complaints that Coinbase granularity now expects a string. Please revert that ASAP. Thanks

**Comment by dthevenin** [comment]
> I think the changes on the Coinbase side look good, have tested them myself and they work
> 
> When using Binance though in the printout i think you should keep it as displaying the original value enetered by the user so there isn't a difference between what is specified as the granularity and what is displayed back

Good point, I went easy here. I will respect the format for the log.

**Comment by dthevenin** [comment]
> Do not make breaking changes. Unifying granularity would not be backward compatible. I don't want people's bots breaking and forcing them to update their config.json's. I want it how it was using the official granularity for the exchanges as per the API documentation. Integer options for Coinbase and string options for Binance. There are complaints that Coinbase granularity now expects a string. Please revert that ASAP. Thanks

@whittlem There is no breaking change here (that I'm aware of), and there is nothing to revert, it's a PR.
The goal  (that I describe in #203) is to use only one format internally in order to simplify the code, make it more robust, easier to test, etc.
The issue you are referencing with Coinbase granularity, is a bug in master that I did fix in that PR (https://github.com/whittlem/pycryptobot/pull/204/commits/eb1e6875d576f8c1bc54c641dfdaa6c8a7ff1bb1) and actually there is another PR in review, that fixes this issue (https://github.com/whittlem/pycryptobot/pull/190).

The point of @marioK93 is that logs use the internal granularity value, which can be confusing for users. I will update that part.

The main issue with that PR, is that I supposed that all exchanges use the same granularity values (which is true for Coinbase and Binance). Maybe another exchange uses different values. If it the case we will figure out what to do the moment we add that new exchange; the future is the future, even a bot can't predict it 😉

**Comment by marioK93** [comment]
Ignore the change I reverted, I accidentally pushed into the wrong PR

**Comment by dthevenin** [comment]
> Ignore the change I reverted, I accidentally pushed into the wrong PR

@marioK93 
No worries. I  will rewrite the commit history and I will do a push force.
Be careful when you pull next time
I do push a fix related to your comment.

**Comment by dthevenin** [comment]
@marioK93 @whittlem I did take into account the logs issue: here some examples of output for Binance
```bash
2021-05-15 21:00:00 | ATMUSDT | 15m | Close: 42.5 | v EMA12/26: 42.85 < 42.95 v | v MACD: -0.1 < -0.04 v | WAIT

2021-05-17 22:35:00 | ATMUSDT | 5m | Close: 46.2 | BUY
 Fibonacci Retracement Levels: {'ratio1': 45.63, 'ratio0_768': 46.74}
 Resistance level of 50.745 formed at 2021-05-18 07:05:00
```

I can't test for Coinbase, please do itv :-)

Cheers

**Comment by whittlem** [comment]
> > Do not make breaking changes. Unifying granularity would not be backward compatible. I don't want people's bots breaking and forcing them to update their config.json's. I want it how it was using the official granularity for the exchanges as per the API documentation. Integer options for Coinbase and string options for Binance. There are complaints that Coinbase granularity now expects a string. Please revert that ASAP. Thanks
> 
> 
> 
> @whittlem There is no breaking change here (that I'm aware of), and there is nothing to revert, it's a PR.
> 
> The goal  (that I describe in #203) is to use only one format internally in order to simplify the code, make it more robust, easier to test, etc.
> 
> The issue you are referencing with Coinbase granularity, is a bug in master that I did fix in that PR (https://github.com/whittlem/pycryptobot/pull/204/commits/eb1e6875d576f8c1bc54c641dfdaa6c8a7ff1bb1) and actually there is another PR in review, that fixes this issue (https://github.com/whittlem/pycryptobot/pull/190).
> 
> 
> 
> The point of @marioK93 is that logs use the internal granularity value, which can be confusing for users. I will update that part.
> 
> 
> 
> The main issue with that PR, is that I supposed that all exchanges use the same granularity values (which is true for Coinbase and Binance). Maybe another exchange uses different values. If it the case we will figure out what to do the moment we add that new exchange; the future is the future, even a bot can't predict it 😉

Ok, perfect. Unifying within the backend is a great idea. I was worried about big user facing changes that would cause confusion and break what they have already but this sounds really good. Thanks

**Comment by whittlem** [comment]
I see there are conflicts in this PR. Is this one finished and ready for review?

**Comment by whittlem** [comment]
The conflict is from the "buymaxsize" but not an issue here. Is this one ready to be merged?

**Comment by whittlem** [comment]
I see another PR which could potentially conflict here... 
https://github.com/whittlem/pycryptobot/pull/218

Can you confirm if it's okay for me to approve it without breaking yours?

**Comment by dthevenin** [comment]
@whittlem it will be OK. I will rebase my branch with main after #218 is merged.

**Comment by dthevenin** [comment]
I will fix conflicts once #218 is merged (Sunday night JST)

**Comment by whittlem** [comment]
Thanks, I merged it. Let me know when this one is ready.

**Comment by dthevenin** [comment]
@whittlem It did rebase with main and push forced. All conflicts are fixed
Its ready.

**Comment by whittlem** [comment]
Thanks, it is still saying there are conflicts. Can you check please?

**Review by whittlem — APPROVED** [review]
Looks great, thanks.

**Comment by whittlem** [comment]
There were two conflicts in pycryptobot.py which I resolved. I took the change from your branch. I then compared the action helper function arguments and they don't match.

This is the definition of the function in the helper file:

def calculate_margin(buy_size: float = 0.0, buy_filled: int = 0.0, buy_price: int = 0.0, buy_fee: float = 0.0,
                     sell_percent: float = 100, sell_price: float = 0.0, sell_fee: float = 0.0,
                     sell_taker_fee: float = 0.0, debug: bool = False) -> float:

Can you please make sure that this is correctly called in the pycryptobot.py? I think I should have taken the change from the main branch. 

Aside from this the change looks good to know. Just message me on Telegram when this has been updated and I'll merge it.

**Comment by dthevenin** [comment]
@whittlem I did fix again the conflicts. You can merge

FYI several tests are not passing anymore on Main and on this PR since I did rebase.

**Pull request merged**
