### PR TITLE
refactor quote currency extraction

### PR DESCRIPTION
**Pull request by lazydroid**
## Description

Nothing major, basically a test PR to make sure I can actually contribute.
Changes to the code include replacing "if-else" with a compact loop.

## Type of change

Please make your selection.

- [ * ] Code Maintainability / comments
- [ * ] Code Refactoring / future-proofing

## How Has This Been Tested?

New code seems to run flawlessly on my PC.

## Checklist:

- [ * ] My code follows the style guidelines of this project
- [ * ] I have performed a self-review of my own code
- [ * ] My changes generate no new warnings
- [ * ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by whittlem** [comment]
@lazydroid, thanks.

Can you please update CHANGELOG.md and increase the version number in README.md to v2.30.2?

**Comment by lazydroid** [comment]
> Can you please update CHANGELOG.md and increase the version number in README.md to v2.30.2?

This PR does not change a lot, and practically invisible to the user, I have more actual changes
that are actually visible, shall I postpone bumping up the version until then?

Just in case you're wondering, I would like to make changes to the way we store API keys from what we have now, basically moving the "secret" part into the `binance.key` or `coinbase.key` files, which are not saved into the repository -- this will allow the serialization and exchange of config files much easier, because people do not need to "censor" their API key/secret every time (and potentially forget that once in a while). The `config.json` will reference ` "api_key_file" : "exchange.key" ` and we will be able to store them into the repo without the risk of exposing secrects. What do you think about this?

**Comment by whittlem** [comment]
I like that idea. Thanks.

I think the options in config.json need to be looked at sometime as well. Aside from separating the keys, the next step would be to look at a more consistent more intuitive way of setting options.

If you separate the keys please make a detect and migrate option. I don't want people's bots to break. Either have code that will detect legacy config and migrate it automatically or allow for backward compatibility. 

In terms of versioning it was decided that all code changes need to be reflected in the version. First number is a major version release, second is a feature release, third is hotfix or small update. If your change is small just increment the last number. If it is a new feature then increment middle number and set last number to 0.

**Comment by lazydroid** [comment]
Bumped the version. Please, continue with the merge.

I can see the migration path as 3 steps:

1. we allow both `"api_key" / "api_secret"` and `"api_key_file"` in the config.json
2. we print the message that the first approach will be discontinued in the future and nudge people to make changes
3. completely disable `"api_key" / "api_secret"` once most people have successfully migrated

**Review by whittlem — APPROVED** [review]
Thanks, looks good.

**Pull request merged**
