### PR TITLE
Create Docker image that runs scanner by default, not the normal bot

### PR DESCRIPTION
**Pull request by marioK93**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

I have simply duplicated the existing DockerFile and workflow that builds it, the only change being the inital command run when the Container starts, pointing it to telegram_bot.py instead

Fixes # (issue)

## Type of change

Please make your selection.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [ ] Code Refactoring / future-proofing

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by loomsen** [comment]
Hi,

I would reject this, as I think it's pointless to introduce code duplication. You can easily use `--entrypoint` in your docker command.
Just my 2ct.

**Comment by marioK93** [comment]
Maybe it was a Portainer bug but changing the entrypoint there wasn't working for me, if adding --entrypoint to the command works though then sure can close the PR

**Comment by warrmr** [comment]
Agreed, override the entry point, its also documented here. 

https://github.com/whittlem/pycryptobot/blob/main/docs/DockerBotSetup.md

If you have an issue running the bot and overriding the entrypoint raise a ticket.  I dont use portainer on my bot setup (No need for a GUI) so cant comment how it works with the bot.
I do use Portainer on my QNAP NAS and have some stuff running through that and I can say that you can setup a "Stack" where you launch the container using a compose file rather than a run command which you should be able to use the compose file linked in the above document and it should be all gravy.

**Comment by marioK93** [comment]
thanks for the help, will look into it again and see if i can fix it on my end, will close this up

**Pull request closed without merging**
