### PR TITLE
Boolean methods

### PR DESCRIPTION
**Pull request by Nicolas469**
## Description

This pull request only change some methods in PyCrypoBot class.
This update methods that should return a boolean instead of an int to clarify the code.

## Type of change

Please make your selection.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [x] Code Refactoring / future-proofing

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by whittlem** [comment]
This looks like a nice update, thanks.

I just want to confirm it doesn't conflict with this:
https://github.com/whittlem/pycryptobot/pull/204

**Comment by Nicolas469** [comment]
I'm pretty sure it doesn't but I will wait @dthevenin to confirm.

**Comment by dthevenin** [comment]
Let’s merge that PR and I will rebase mine

**Review by googiealas — APPROVED** [review]
changes looks good to me

**Comment by whittlem** [comment]
Thanks for the help reviewing. Merging this one now.

**Pull request merged**
