### PR TITLE
Fix default config creation

### PR DESCRIPTION
**Pull request by lazydroid**
## Description

1. Default to the config creation if there's none to benefit the new users
2. Skip creating the empty config -- this is a bit disorienting for people who always press "Enter" and end up with empty config

## Type of change

Please make your selection.

- [ * ] Bug fix (non-breaking change which fixes an issue)
- [ * ] New feature (non-breaking change which adds functionality)
- [ maybe ] This change requires a documentation update
- [ * ] Code Maintainability / comments
- [ * ] Code Refactoring / future-proofing

## How Has This Been Tested?

Runs well on my PC.

## Checklist:

- [ * ] My code follows the style guidelines of this project
- [ * ] I have performed a self-review of my own code
- [ * ] New and existing unit tests pass locally with my changes
- [ * ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by whittlem** [comment]
@lazydroid, thanks but something has broken as the unit tests are failing.

**Comment by lazydroid** [comment]
@whittlem fresh checkout gives me plenty of errors:
```
$ git clone https://github.com/whittlem/pycryptobot.git www
Cloning into 'www'...
remote: Enumerating objects: 2806, done.
remote: Counting objects: 100% (1837/1837), done.
remote: Compressing objects: 100% (820/820), done.
remote: Total 2806 (delta 1195), reused 1258 (delta 1017), pack-reused 969
Receiving objects: 100% (2806/2806), 2.38 MiB | 9.46 MiB/s, done.
Resolving deltas: 100% (1838/1838), done.
$ cd www
~/www$ pytest
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/lenik/www, configfile: pytest.ini
collected 117 items                                                            

tests/integration_tests/test_model_exchange_binance.py .....FFFFFFFFFFFF [ 14%]
FFFFFFFFFF                                                               [ 23%]
tests/integration_tests/test_model_exchange_coinbase_pro.py ......FFFFFF [ 33%]
FFFFFFFFFFFFFFFFFFF                                                      [ 49%]
tests/unit_tests/test_binance.py ......EEEEs                             [ 58%]
tests/unit_tests/test_formatting.py ........                             [ 65%]
tests/unit_tests/test_margin_calculation.py ...........                  [ 75%]
tests/unit_tests/test_model_pycryptobot.py ............................. [100%]
```

most of them are `FileNotFoundError: [Errno 2] No such file or directory: 'config.json'` -- am I doing something wrong?

**Comment by lazydroid** [comment]
@whittlem could you please take a look at this?

I don't see what the error is in CI tests, it just says "Error:" and that's it.
Makes it a bit hard to fix, since I have no idea what's broken...

**Comment by whittlem** [comment]
@lazydroid, run this:
pytest -s tests/unit_tests/test_model_pycryptobot.py -k 'test_instantiate_model_without_error'

This test is failing from your change.

At a basic level this has broken...

from models.PyCryptoBot import PyCryptoBot
app = new PyCryptoBot()

**Comment by lazydroid** [comment]
@whittlem I'm not sure if `new PyCryptoBot()` is valid syntax, Python does not use `new`.

Otherwise, the test you mentioned passes on my PC, could you please tell me more about what's broken?
```
$ git checkout dev/lenik/fix_default_config 
Switched to branch 'dev/lenik/fix_default_config'
Your branch is up to date with 'origin/dev/lenik/fix_default_config'.
$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from models.PyCryptoBot import PyCryptoBot
>>> app = PyCryptoBot()
>>> 
$ pytest -s tests/unit_tests/test_model_pycryptobot.py -k 'test_instantiate_model_without_error'
============================== test session starts ==============================
platform linux -- Python 3.6.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/lenik/whittle, configfile: pytest.ini
plugins: mock-3.6.1
collected 29 items / 28 deselected / 1 selected                                 

tests/unit_tests/test_model_pycryptobot.py .

======================= 1 passed, 28 deselected in 0.91s ========================
~/whittle$
```

My changes were mostly to `ConfigBuilder.py`, in `PyCryptoBot.py` I have changed 2 (two) lines and for the love of God could not figure out how those changes could possibly break anything.

Again, the main purpose of the changes I did was to create a config file by default, probably some of the tests did not expect that and should be changed to accommodate for the new behaviour?

**Comment by lazydroid** [comment]
@whittlem  i have changed the test to accommodate for the new behaviour. please check the changes and make sure this looks good.

**Pull request merged**
