### PR TITLE
Added documentation for docker-compose. Create template for docker-compose

### PR DESCRIPTION
**Pull request by letsautom8**
Added documentation for docker-compose. 
Create template for docker-compose.

### CODE REVIEW

**Comment by whittlem** [comment]
@letsautom8, what does this do in the README.md?

[Docker](https://github.com/whittlem/pycryptobot/actions/workflows/docker-publish.yml)

I tried opening "https://github.com/whittlem/pycryptobot/actions/workflows/docker-publish.yml/badge.svg" in my browser and it says that file is not found.

**Comment by letsautom8** [comment]
My guess is that it's from your github workflow. I'm not really sure what is that for. It was from this commit 
https://github.com/whittlem/pycryptobot/commit/f5db33a0238168da57166a7c887b3e2d7a848ee1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by whittlem** [comment]
Sorry, I thought you added it. Looks like @lvlie added it. @lvlie, any ideas?

**Comment by lvlie** [comment]
Yeah that is a mistake. The badge should refer to the container.yml build pipeline, instead of docker-publish. Changed that name last minute but forgot to change the status badge...

**Comment by whittlem** [comment]
Fixed, thank you.

**Pull request closed without merging**
