### PR TITLE
Added startdate and merge function to stats module

### PR DESCRIPTION
**Pull request by hebawom**
## Description

2 new flags:
--statstartdate: This creates stats only using trades that happened more recently than the given date.
--statgroup: This is a list of currency pairs that get merged for the stats. e.g on command line:
`python pycryptobot.py --stats --statgroup BTCGBP ETHGBP ADAGBP --statstartdate 2021-06-01`
In config.json would look like this:
```
"stats": 1,
"statgroup": ["BTCGBP", "ADAGBP", "ETHGBP"]
```
This requires that the currency pairs have the same quote currency (code checks for this)

## Type of change

Please make your selection.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [ ] Code Refactoring / future-proofing

## How Has This Been Tested?

Ran unit tests
Tested with my own data (binance only)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by hebawom** [comment]
I know noone has asked for these changes, but I wrote them for myself and thought I'd share.

**Comment by whittlem** [comment]
@hebawom, thanks for taking the initiative. This looks great.

Can you please update the README.md which has the arguments all documented? Thanks

**Comment by whittlem** [comment]
@hebawom, the version will be 2.38.0 as you are adding a new feature. 2.37.3 would be if you were fixing something.

**Comment by hebawom** [comment]
I've done that. Michael, did you have a look at your LTC orders.
It was reporting massive losses for you last time.
If it reports transfers out of the account as an 'sell' action - makes stats completely useless!

**Comment by hebawom** [comment]
In the live orders, coinbase pro was giving the 'sell' size as the crypto currency size and not the quote currency size (as binance does). Added a calculation based on exchange

**Review by whittlem — APPROVED** [review]
Looks great, thank you.

**Pull request merged**
