### PR TITLE
Fix exception when saving CSV

### PR DESCRIPTION
**Pull request by rcarmo**
# Fix Latest Commit to Main

## Description

The removal of the `.astype` calls in the previous commit to `main` causes an exception when saving the CSV file:

```bash
Traceback (most recent call last):
  File "../../pycryptobot.py", line 964, in main
    executeJob(s, app, state)
  File "../../pycryptobot.py", line 925, in executeJob
    account.saveTrackerCSV()
  File "/home/sandbox/pycryptobot/models/TradingAccount.py", line 363, in saveTrackerCSV
    df_tracker['profit'] = np.subtract(np.subtract(df_tracker['sell_value'], df_tracker['buy_value']), np.add(df_tracker['buy_fees'], df_tracker['sell_fees']))
  File "/usr/lib/python3/dist-packages/pandas/core/series.py", line 812, in __array_ufunc__
    result = ops.maybe_dispatch_ufunc_to_dunder_op(
  File "/usr/lib/python3/dist-packages/pandas/core/ops/__init__.py", line 1740, in maybe_dispatch_ufunc_to_dunder_op
    return getattr(self, name, not_implemented)(inputs[1])
  File "/usr/lib/python3/dist-packages/pandas/core/ops/__init__.py", line 1048, in wrapper
    result = na_op(lvalues, rvalues)
  File "/usr/lib/python3/dist-packages/pandas/core/ops/__init__.py", line 970, in na_op
    result = masked_arith_op(x, y, op)
  File "/usr/lib/python3/dist-packages/pandas/core/ops/__init__.py", line 447, in masked_arith_op
    result[mask] = op(xrav[mask], com.values_from_object(yrav[mask]))
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

## Type of change

Please make your selection.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

This is another change to my currently running instance, which I just merged from main.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by whittlem** [comment]
This is great, thank you.

**Comment by whittlem** [comment]
There is a merge conflict. Which one do you want to keep?

<<<<<<< patch-1
                    if self.die_on_api_error:
                        raise SystemExit('JSONDecodeError: ' + self._api_url)
                    else:
                        print ('JSONDecodeError: ' + self._api_url)
                        return pd.DataFrame()
    =======
                    print (err)
                    return pd.DataFrame()
            else:
                if self.die_on_api_error:
                    raise SystemExit(f"{reason}: {self._api_url}")
                else:
                    print(f"{reason}: {self._api_url}")
                    return pd.DataFrame()
    >>>>>>> main

**Comment by rcarmo** [comment]
Fixed it. In the meantime I'm going over the files in my own fork and trying to tidy up things like messages, error handling, etc.

Will try to submit readable PRs for those, file per file so it's easier to digest.

**Comment by whittlem** [comment]
> Fixed it. In the meantime I'm going over the files in my own fork and trying to tidy up things like messages, error handling, etc.
> 
> Will try to submit readable PRs for those, file per file so it's easier to digest.

That's great, thank you very much.

I am also working my way through:
https://www.codefactor.io/repository/github/whittlem/pycryptobot

**Pull request merged**
