### PR TITLE
fix sim Index error

### PR DESCRIPTION
**Pull request by markhollingworth-worthit**
## Description

-- fix for sim index "IndexError('index 0 is out of bounds for axis 0 with size 0')"
-- moved trades csv file to CSV folder

Fixes # (issue)

## Type of change

Please make your selection.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [x] Code Refactoring / future-proofing

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- x ] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by whittlem** [comment]
@markhollingworth-worthit, this is great. I don't suppose you can make the "CSV" folder lowercase "csv"? Very rarely on linux based systems you see uppercase directories.

**Comment by markhollingworth-worthit** [comment]
> @markhollingworth-worthit, this is great. I don't suppose you can make the "CSV" folder lowercase "csv"? Very rarely on linux based systems you see uppercase directories.

Yes I will make that change

**Comment by markhollingworth-worthit** [comment]
@whittlem I have updated the folder and commit the change here

**Comment by juancastilla** [comment]
I'm hitting this error when running fast simulations

image

Interestingly I don't get the error for some pairs such as SOL/USDT

**Review by whittlem — APPROVED** [review]

**Pull request merged**
