### PR TITLE
Convert truncated quote currency value to float for marketBuy

### LINKED ISSUE #248: TypeError: The funding amount is not numeric
Describe the bug:
The bot fails to buy and returns an exception when buying via Coinbase API

To Reproduce:
When bots make a purchase via Coinbase API

Expected behavior:
The bot knew conditions were right to buy, the bot checks the balance and can see there is GBP in there. However, the following exception then occurs: TypeError('The funding amount is not numeric.').

Desktop (please complete the following information):
 - Mac OS 11.3.1 (20E241)
 - Visual Studio Code
 - Version: 1.56.2

Log file attached.

[log.txt](https://github.com/whittlem/pycryptobot/files/6544221/log.txt)

### PR DESCRIPTION
**Pull request by happz**
## Description

Convert truncated quote currency value to float for marketBuy

Fixes #248

## Type of change

Please make your selection.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [ ] Code Refactoring / future-proofing

## How Has This Been Tested?

Manual runs.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Nicolas469** [comment]
Wouldn't be better to just remove the truncate ?
If the bot wants to buy BTC, the precision should be more than 2.

**Comment by happz** [comment]
> Wouldn't be better to just remove the truncate ?
> If the bot wants to buy BTC, the precision should be more than 2.

I'd say yes, but I don't know enough. I'd be fine with it, let's wait for @whittlem - for some reason, `truncate()` was and is there, the problem is it used to return float when called like this, now it doesn't. Therefore, yes, I'd say it's safe to remove, but I don't know for sure.

**Comment by plitex** [comment]
Hi guys, do you know when this broken? Just to know which version isn't affected.

**Review by whittlem — APPROVED** [review]

**Comment by whittlem** [comment]
The exchanges require markets to trade with specific precision. Each market has its own trading rules. In most cases it will just work but if someone tries to put a trade through with high precision it will fail. This is to prevent that.

**Pull request merged**
