### PR TITLE
Fix JSON typo in values.yaml example

### PR DESCRIPTION
**Pull request by Dwaynekj**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Minor typo in the helm chart example json

Fixes # (issue)

## Type of change

Please make your selection.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [ ] Code Refactoring / future-proofing

## How Has This Been Tested?

Deployed in my own GKE cluster

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added pytest unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by edrickrenan — APPROVED** [review]

**Comment by loomsen** [comment]
Thanks, but please target the beta branch.

**Review by loomsen — CHANGES_REQUESTED** [review]
target branch should be `whittlem:beta` not `main`

**Review by lazydroid — APPROVED** [review]
LGTM!

**Review by lazydroid — APPROVED** [review]
LGTM!

**Review by loomsen — APPROVED** [review]
Lgtm

**Pull request merged**
