### PR TITLE
Using enum instead of strings when comparing exchanges

### PR DESCRIPTION
**Pull request by edrickrenan**
## Description

Reading the code, I noticed a lot of places where exchanges were declared as literal strings, so I decided to create an enum for the exchanges so they could be in a centralized location.  This will decrease the chances of a bug due to a typo.

## Type of change

Please make your selection.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [x] Code Maintainability / comments
- [x] Code Refactoring / future-proofing

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added pytest unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by notoriousBLP — COMMENTED** [review]
how does this reduce the chance for a typo? one is typing more letters in every instance.

'binance' vs. 'Exchange.BINANCE.value'

**Comment by edrickrenan** [comment]
@notoriousBLP, because right now you could create an if condition with anything similar to `binance`, for example, `binonce`, and it could be approved and merged here. With the implementation of enums, we can guarantee that such mistakes are not made, because any typo there will throw an exception saying that the enum value is invalid.

Apart from that, I find it better than having the same string duplicated at least 30 times in different parts of the code.

Anyway, that's a proposal, the PR can be closed if the people feel that is not worth it.

**Comment by cebas** [comment]
+1 for the proposal.
The IDE can help typing enums showing options and preventing errors before even running. It can't help typing strings...
I also think that comparing enums might be more efficient than comparing strings, runtime wise.

**Comment by notoriousBLP** [comment]
> @notoriousBLP, because right now you could create an if condition with anything similar to `binance`, for example, `binonce`, and it could be approved and merged here. With the implementation of enums, we can guarantee that such mistakes are not made, because any typo there will throw an exception saying that the enum value is invalid.
> 
> Apart from that, I find it better than having the same string duplicated at least 30 times in different parts of the code. Plus, any good IDE will suggest the enum values, so you don't have to type that yourself.
> 
> Anyway, that's a proposal, the PR can be closed if the people feel that is not worth it.

makes sense to me...thanks

**Comment by edrickrenan** [comment]
> +1 for the proposal. The IDE can help typing enums showing options and preventing errors before even running. It can't help typing strings... I also think that comparing enums might be more efficient than comparing strings, runtime wise.

Yes. I was considering that when making these changes. If this gets approved and merged, I'll try to work on converting the exchanges to enum in the config parser, so we can compare enums.

**Review by whittlem — APPROVED** [review]

**Comment by whittlem** [comment]
Thanks, looks good.

**Pull request merged**
