### PR TITLE
added statdetail flag

### PR DESCRIPTION
**Pull request by hebawom**
## Description

adds new flag to stats module '--statdetail' which gives more detail for each transaction

Screenshot 2021-06-30 at 11 53 09

## Type of change

Please make your selection.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [ ] Code Refactoring / future-proofing

## How Has This Been Tested?

Tested with transactions from both binance and coinbase pro. unit tests pass.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by lazydroid** [comment]
Could you please fill the template, especially the parts "description" and "how this has been tested" ?

That's going to help reviewers a lot! =)

**Comment by hebawom** [comment]
I did fill that bit in? I can't really add more detail to it. I tested it with my own data in both exchanges.

**Comment by hebawom** [comment]
I guess I could add more to the 'description' bit. Output of --statdetail would look like this:


Screenshot 2021-06-30 at 11 53 09

**Comment by hebawom** [comment]
> Could you please fill the template, especially the parts "description" and "how this has been tested" ?
> 
> That's going to help reviewers a lot! =)

Ah, I'm guessing you didn't see what I had written under those headers (just looked at your PR and you've deleted the template text).

**Comment by lazydroid** [comment]
thanks! much clearer now!

**Comment by whittlem** [comment]
This is great, thanks

**Pull request merged**
