### PR TITLE
telegram bot control file fixes

### PR DESCRIPTION
**Pull request by markhollingworth-worthit**
## [5.2.5] - 2022-01-20

- more exception handling added for JSONDecode errors
- fixed Telegram Reload config market not valid error
- added telegram_bot log file and telegram_logs folder

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [ ] Code Refactoring / future-proofing

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by whittlem** [comment]
@markhollingworth-worthit, I resolved the conflicts with CHANGELOG.md and README.md. Please can you fix the pycryptobot.py conflict? Thanks

**Comment by whittlem** [comment]
@markhollingworth-worthit, actually it won't let me commit the CHANGELOG.md and README.md fixes without the pycryptobot.py conflict fixed at the same time. I think we should be on the .5 version. We don't need to keep incrementing the versions in beta or there will be massive jumps when it's merged into main.

**Comment by whittlem** [comment]
@markhollingworth-worthit, any luck with resolving the conflicts? I can't merge this.

**Comment by markhollingworth-worthit** [comment]
@whittlem conflicts have been resolved

**Pull request merged**
